In [ ]:
import pandas as pd

In [2]:
# Realizar esse processo para cada dataset da pasta uploads
arquivo_csv = ('dataclean/analise_txcg_jan_2025.csv')
df = pd.read_csv(arquivo_csv, sep='#', encoding='utf-8-sig')
print(df.shape)

C:\Users\jcpsrodrigues\AppData\Local\Temp\ipykernel_20380\4249525255.py:3: DtypeWarning: Columns (5,20,43,54,60,61) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(arquivo_csv, sep='#', encoding='utf-8-sig')

(1762248, 64)

In [4]:
df.head()

,processo_id,comarca,comarca_id,entrancia,serventia,codg_serventia_cnj,vara_oficial_id,origem,is_conhecimento,grupo_cnj_id,...,nome_comarca_origem,codg_atividade,data_remessa_instancia_inferior,is_desconsiderar_estatistica,is_acao_coletiva,data_julgamento_considerada,gabinete,codg_gabinete_cnj,gabinete_codigo_cnj,vara_oficial_codigo_cnj
0,255,ABADIÂNIA,1,INICIAL,Vara Judicial,NaN,42,PROJUDI,f,4,...,NaN,NaN,NaN,f,f,2024-07-05,NaN,NaN,NaN,11501
1,4201784,ABADIÂNIA,1,INICIAL,Vara Judicial,NaN,42,PROJUDI,t,4,...,NaN,NaN,NaN,f,f,NaN,NaN,NaN,NaN,11501
2,197,ABADIÂNIA,1,INICIAL,Vara Judicial,NaN,42,PROJUDI,f,4,...,NaN,NaN,NaN,f,f,NaN,NaN,NaN,NaN,11501
3,4039180,ABADIÂNIA,1,INICIAL,Vara Judicial,NaN,42,PROJUDI,f,4,...,NaN,NaN,NaN,f,f,NaN,NaN,NaN,NaN,11501
4,65335,ABADIÂNIA,1,INICIAL,Vara Judicial,NaN,42,PROJUDI,f,4,...,NaN,NaN,NaN,f,f,2016-03-28,NaN,NaN,NaN,11501

In [ ]:

filtro = (
    (df['comarca'] == 'APARECIDA DE GOIÂNIA') & 
    (df['serventia'] == '1ª Vara Cível') &
    (df['data_distribuicao'])
)
df[filtro].head()

,processo_id,comarca,comarca_id,entrancia,serventia,codg_serventia_cnj,vara_oficial_id,origem,is_conhecimento,grupo_cnj_id,...,nome_comarca_origem,codg_atividade,data_remessa_instancia_inferior,is_desconsiderar_estatistica,is_acao_coletiva,data_julgamento_considerada,gabinete,codg_gabinete_cnj,gabinete_codigo_cnj,vara_oficial_codigo_cnj
198496,6471221,APARECIDA DE GOIÂNIA,9,FINAL,1ª Vara Cível,NaN,60,PROJUDI,t,4,...,NaN,NaN,NaN,f,f,NaN,NaN,NaN,NaN,11448
198497,6513099,APARECIDA DE GOIÂNIA,9,FINAL,1ª Vara Cível,NaN,60,PROJUDI,t,4,...,NaN,NaN,NaN,f,f,NaN,NaN,NaN,NaN,11448
198498,6476602,APARECIDA DE GOIÂNIA,9,FINAL,1ª Vara Cível,NaN,60,PROJUDI,t,4,...,NaN,NaN,NaN,f,f,NaN,NaN,NaN,NaN,11448
198499,6509806,APARECIDA DE GOIÂNIA,9,FINAL,1ª Vara Cível,NaN,60,PROJUDI,t,4,...,NaN,NaN,NaN,f,f,NaN,NaN,NaN,NaN,11448
198500,6461782,APARECIDA DE GOIÂNIA,9,FINAL,1ª Vara Cível,NaN,60,PROJUDI,f,4,...,NaN,NaN,NaN,f,f,NaN,NaN,NaN,NaN,11448

In [18]:
print(df[filtro].shape)

(6541, 64)

In [13]:
baixados = df[filtro]['data_baixa'].notna().sum()
print(baixados)

135

In [15]:
pendentes = df.loc[filtro, 'data_baixa'].isna().sum()
print(pendentes)

6406

In [19]:
tx_cong_global = (100 * pendentes/(pendentes+baixados)).round(2)
print(f"Taxa de Congestionamento Global: {tx_cong_global} %")

Taxa de Congestionamento Global: 97.94 %

In [6]:
dist = df[filtro]['data_distribuicao'].notna().sum()
print(dist)

6541

In [8]:
df['data_distribuicao'] = pd.to_datetime(df['data_distribuicao'], errors='coerce') 

dist_2025 = (df[filtro]['data_distribuicao'].dt.year == 2025).sum()
print(dist_2025)

239